-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "laundry";

-- CreateEnum
CREATE TYPE "laundry"."UserRole" AS ENUM ('customer', 'staff', 'admin', 'hub_manager');
CREATE TYPE "laundry"."StaffRole" AS ENUM ('pickup', 'delivery', 'hub_operator', 'manager');
CREATE TYPE "laundry"."OrderStatus" AS ENUM ('draft', 'pending_confirmation', 'confirmed', 'pickup_assigned', 'pickup_in_progress', 'picked_up', 'verification_pending', 'in_processing', 'ready_for_delivery', 'out_for_delivery', 'delivered', 'cancelled', 'exception');
CREATE TYPE "laundry"."PaymentStatus" AS ENUM ('unpaid', 'pending', 'paid', 'refunded');
CREATE TYPE "laundry"."AssignmentType" AS ENUM ('pickup', 'delivery');

-- Note: run `npx prisma db push` or `npx prisma migrate deploy` against your DATABASE_URL.
-- Full DDL is generated by Prisma from schema.prisma on first migrate.
